language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libusb-1.0-0-dev
    - libudev-dev

services:
  - docker
  
script: docker build -t diefarbe/sich-ausruhen .

deploy:
  provider: script
  script: bash travis_dockerpush.sh
  on:
    branch: master
  skip_cleanup: true

env:
  global:
    - DOCKER_USERNAME=chris13524
    - secure: XJwW8KSHKxTb7nkiGjW6kkJQGiCWLZAwdb6Sf1ivsI59kL+6mGMpspBd4M4MNbJFvK/r452Z0swzDrPbU4WEBmkhG2n0tV7Rwohe6ZDaujHaMYfOlAgtG0i+jzGErcmb5R96mla1/DTvptSt1Ex3gCY2aeg+ciLzacA9EO2DW+nVRoBsm19D8SctuFLPiPKcv11vehWo6lcL7ecG/o5nDF2XdthsaJoBPZDe450VMznOdzrJsB9MoZiFFYb+F4azl1TSe6d1tr0O+v8kb7QZaYYlFW6u/N9NT8e/xBIkEWEXNJHJThgk4GrbqcMqBjDzlhZZOZGYd/AqzYVIO+eFn1wnXfaZmo8LT+bMWd93Kr/FexixI800gQ2YEj52D0tLoDnb9f+1oYZLRTXatNv/2xxZ4zLM19NlRkXSS1KyUzhJ2FEPFcfq4MIKQJOR0OUPPu6GlMTJNTTyHv92IOce8nY+2lFRs75ALAX1Tne78+s29l/5Q8y6h7I6zEltjgzvdWTosJLvBweZw/Z2HamGSGn8gyCuoo1dcyTbgY1YrfvGMKXHkCeWuzibS9Ted3e2/gj+aQDSA1ZKrymeGhmtxLIcSDZSUcS0zQMrhhPcLk0Y7zJ6LrYiX21Bku9+xKOJDf96TJGFUBLCAc5AOUXhC7GI6L51dWjq4YbFqZf8L2o=
