language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - gcc-multilib
    - libusb-1.0-0-dev
    - libudev-dev

services:
  - docker
  
script: docker build -t diefarbe/sich-ausruhen .

deploy:
  provider: script
  script: travis_dockerpush.sh
  on:
    branch: master

env:
  global:
    - DOCKER_USERNAME=chris13524
    - secure: RB2crI9n0Gxv2lm4CxtB/AL8ezvq+9yF1G/lt6wsk4SqqBHck5oPpOmYNLweRlrcOWD4i7PyS2ZYc/bxBSLF8epd1TP6Und+/73rkmIlZHC46nHWFMCGWiyfyutOSjjc51nTbfCfzmNm9INo9T7KgEGsIXYOC3PBjaw80boV1UmDsrLqb6WGu7rLaiVJLlwThaJVMUBBD+ijMa+xOTf6Ok4YLtHYfDBaaB+mnx7Ng5mF2S62Ff4V1AVG5bLZ1hc2IN+QJCIcCTuG0JT/C6svk1YHblKjtkjCXN6t9YblgJjCp8GRN9PKg4z1Bo9IKWISFEX7/mV2eQV/1EetBT5LT51vOPgcmJja2CBSrzl3DOTgWeNWXZWCF1PpCBY0yhS1P9u4OemRG4e/JhrIX/cdhOHZewhflhJbHbUjAXO8LtiKCc8uZIW64FDsjmegajdor/nPV+P8cp/Oys0ft7T87OaVpLxAuw7JC5NHlvpDE8WEvFn6oqU5UKeRM2JhnjO7wCUUZ6+NxZQbH0RagLPbVjVMunhj9JGFYwn7PrV2DLIHpF0t2kIkJ9Ud4fd8Yc8Kl90FtardMe99I92W32Re3nCmQExvVA/MtnGbHP/oaQzfHsiR2mM8p1rh68snp8i2My85e3XXMSdSUOM+ppO0EX5U2HxVPXavnq41zQhwygA=
